DROP TABLE IF EXISTS PRODUTO;
CREATE TABLE PRODUTO (
    COD_PRODUTO CHAR(4) PRIMARY KEY NOT NULL,
    DES_PRODUTO VARCHAR(30),
    STA_STATUS CHAR(1)
);

DROP TABLE IF EXISTS PRODUTO_COSIF;
CREATE TABLE PRODUTO_COSIF (
    COD_PRODUTO CHAR(4) NOT NULL,
    COD_COSIF CHAR(11) NOT NULL,
    COD_CLASSIFICACAO CHAR(6),
    STA_STATUS CHAR(1),
    CONSTRAINT PRODUTO_COSIF_PK PRIMARY KEY (
        COD_PRODUTO, 
        COD_COSIF
    ),
    CONSTRAINT PRODUTO_COSIF_COD_PRODUTO_FK FOREIGN KEY (
        COD_PRODUTO
    ) REFERENCES PRODUTO (COD_PRODUTO)
);

DROP TABLE IF EXISTS MOVIMENTO_MANUAL;
CREATE TABLE MOVIMENTO_MANUAL (
    DAT_MES NUMERIC(2,0) NOT NULL,
    DAT_ANO NUMERIC(4,0) NOT NULL,
    NUM_LANCAMENTO NUMERIC(18,0) NOT NULL,
    COD_PRODUTO CHAR(4) NOT NULL,
    COD_COSIF CHAR(11) NOT NULL,
    DES_DESCRICAO VARCHAR(50) NOT NULL,
    DAT_MOVIMENTO SMALLDATETIME NOT NULL,
    COD_USUARIO VARCHAR(15) NOT NULL,
    VAL_VALOR NUMERIC(18,2) NOT NULL,
    CONSTRAINT MOVIMENTO_MANUAL_PK PRIMARY KEY (
        DAT_MES,
        DAT_ANO,
        NUM_LANCAMENTO,
        COD_PRODUTO, 
        COD_COSIF
    ),
    CONSTRAINT MOVIMENTO_MANUAL_COD_PRODUTO_COSIF_FK FOREIGN KEY (
        COD_PRODUTO, COD_COSIF
    ) REFERENCES PRODUTO_COSIF (
        COD_PRODUTO, COD_COSIF
    )
);
