DELETE FROM MOVIMENTO_MANUAL;
DELETE FROM PRODUTO_COSIF;
DELETE FROM PRODUTO;

INSERT INTO PRODUTO VALUES ('001','DESC 001','A');
INSERT INTO PRODUTO VALUES ('002','DESC 002','A');
INSERT INTO PRODUTO VALUES ('003','DESC 003','A');

INSERT INTO PRODUTO_COSIF VALUES ('001','COSIF-1','CLA','A');
INSERT INTO PRODUTO_COSIF VALUES ('001','COSIF-2','CLB','A');
INSERT INTO PRODUTO_COSIF VALUES ('002','COSIF-1','CLA','A');
INSERT INTO PRODUTO_COSIF VALUES ('002','COSIF-2','CLB','A');
INSERT INTO PRODUTO_COSIF VALUES ('003','COSIF-1','CLA','A');
INSERT INTO PRODUTO_COSIF VALUES ('003','COSIF-2','CLB','A');

INSERT INTO MOVIMENTO_MANUAL (DAT_MES,DAT_ANO,NUM_LANCAMENTO,COD_PRODUTO,COD_COSIF,DES_DESCRICAO,DAT_MOVIMENTO,COD_USUARIO,VAL_VALOR
) VALUES (2,2019,1,'001','COSIF-1','Descricao movimento 1',now(),'rubens',150.0);
INSERT INTO MOVIMENTO_MANUAL (DAT_MES,DAT_ANO,NUM_LANCAMENTO,COD_PRODUTO,COD_COSIF,DES_DESCRICAO,DAT_MOVIMENTO,COD_USUARIO,VAL_VALOR
) VALUES (2,2019,1,'002','COSIF-1','Descricao movimento manual 2',now(),'rubens',250.89);
INSERT INTO MOVIMENTO_MANUAL (DAT_MES,DAT_ANO,NUM_LANCAMENTO,COD_PRODUTO,COD_COSIF,DES_DESCRICAO,DAT_MOVIMENTO,COD_USUARIO,VAL_VALOR
) VALUES (2,2019,1,'002','COSIF-2','Descricao movimento manual 3',now(),'rubens',300);
